Change: temporary sync into working directory

diff --git a/bin/clam b/bin/clam
--- a/bin/clam
+++ b/bin/clam
@@ -2,6 +2,15 @@
 
 set -euo pipefail
 
+if [[ ${CLAM_DEBUG:-} ]]; then
+  set -x
+fi
+
+if [[ -z ${CLENV_ENVIRONMENT:-} ]]; then
+  echo "CLENV_ENVIRONMENT not set! Please run 'clenv use \$env'." >&2
+  exit 1
+fi
+
 git_sync() {
   local _target=$1
   local _dest=$2
@@ -10,51 +19,75 @@ git_sync() {
     cd $_dest
     git pull
   else
-    git clone ${_target} ${_dest}
+    git clone --depth=1 ${_target} ${_dest}
     cd $_dest
   fi
 }
 
 target=$1
-if [ -d $target -a -r ${target}/clam.spec ]; then
-  mode=copy
+
+mode=""
+module=""
+
+if [ -d $target ]; then
   _path=$(cd $target; pwd)
   module=${_path##*/}
-else
-  mode=git
+  if [ -r ${target}/clam.spec ]; then
+    mode=copy
+  else
+    echo "clam.spec file not found! Can't install." >&2
+    exit 1
+  fi
+fi
+
+mode=${mode:-git}
+if [[ -z $module ]]; then
   module=${target##*/}
   module=${module%.git}
 fi
 
-dest_dir=${CLENV_ROOT}/environments/${CLENV_ENVIRONMENT}/modules
-dest_module=${dest_dir}/${module}
+workdir=${CLENV_ROOT}/tmp/${module}
 
-echo "Sync ${target} into ${dest_module}"
+echo "Sync ${target} into working directory"
 case "$mode" in
   "copy" )
-    cp -rp $target $dest_module
+    cp -rp $target $workdir
     ;;
   "git" )
-    git_sync $target $dest_module
+    git_sync $target $workdir
     ;;
   * )
     ;;
 esac
 
-bin_dir=${CLENV_ROOT}/environments/${CLENV_ENVIRONMENT}/bin
-lib_dir=${CLENV_ROOT}/environments/${CLENV_ENVIRONMENT}/lib
+cleanup() {
+  rm -rf $workdir
+}
 
-cd $dest_module
+cd $workdir
 
 if [ -r clam.spec ];then
   unset version
   unset executables
   unset resources
   source clam.spec
+  version=${version:-noversion}
 else
   echo "clam.spec file not found! Can't install." >&2
+  cleanup
   exit 1
 fi
+
+dest_dir=${CLENV_ROOT}/environments/${CLENV_ENVIRONMENT}/modules
+dest_module=${dest_dir}/"${module}"
+
+cp -rp $workdir $dest_module
+echo "Sync ${module} into ${dest_module}"
+cd $dest_module
+cleanup
+
+bin_dir=${CLENV_ROOT}/environments/${CLENV_ENVIRONMENT}/bin
+lib_dir=${CLENV_ROOT}/environments/${CLENV_ENVIRONMENT}/lib
 
 abspath() {
   local _file=$1
@@ -65,13 +98,13 @@ abspath() {
 install_materials() {
   local _src=$1
   local _dest=$2
-  local f _path
+  local f __path
 
   if [[ $_src ]]; then
     for f in $(\ls -1 $_src); do
       if [ -f $f ]; then
-        _path=$(abspath $f)
-        ln -s ${_path} ${_dest}/
+        __path=$(abspath $f)
+        ln -s ${__path} ${_dest}/
       else
         echo "Not exist $f Skip." >&2
       fi
@@ -82,7 +115,7 @@ install_materials() {
 install_materials "${executables:-}" $bin_dir
 install_materials "${resources:-}" $lib_dir
 
-echo "Installed ${module} ${version:-}"
+echo "Installed ${module} ${version}"
 
 exit 0
 
