[cload] Enhance: load clenv libraries using 'clenv environ'

diff --git a/bin/cload b/bin/cload
--- a/bin/cload
+++ b/bin/cload
@@ -4,9 +4,11 @@ set -euo pipefail
 
 version="0.5.0"
 
-bin_dir=$(cd $(dirname $0) && pwd)
-lib_dir=$(cd ${bin_dir}/../shrc.d && pwd)
-source ${lib_dir}/cload.shrc
+base_dir="$(cd $(dirname $0)/.. && pwd)"
+shrc_dir="${base_dir}/shrc.d"
+lib_dir="${base_dir}/lib"
+source "${shrc_dir}/cload.shrc"
+source "${lib_dir}/cload/clenv.bashrc"
 
 [[ ${CLOAD_DEBUG:-} ]] && set -x
 
@@ -35,20 +37,22 @@ case "$arg" in
   "--version" )
     version --verbose ;;
   "-" )
-    echo ". ${lib_dir}/cload.shrc"
+    echo ". '${shrc_dir}/cload.shrc'"
     exit
     ;;
   * ) ;;
 esac
 
+prepare_clenv_for_cload
+
 shrc="$arg"
-shrc_path=$(cload_search $shrc) || :
-if [[ $shrc_path ]]; then
-  echo ". $shrc_path"
+shrc_path="$(cload_search $shrc)" || :
+if [[ "$shrc_path" ]]; then
+  echo ". '$shrc_path'"
   exit 0
 fi
 
-echo "Can't load $shrc." >&2
+echo "cload: '$shrc' not found" >&2
 
 exit 1
 
